=== Ayoub-etoullali/Activites-Pratiques-XML-And-Semantic-Web/Séances/Séance 1/Prof/rep.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT repertoire (contact)* >
<!ATTLIST repertoire maj CDATA "2022-09-21" >
<!ELEMENT contact (nom, prénom?, téléphone+, email*) >
<!ATTLIST contact 
            id ID #REQUIRED
            type (ami|pro) "ami" >


<!ELEMENT nom (#PCDATA) >
<!ELEMENT prénom (#PCDATA) >
<!ELEMENT téléphone (#PCDATA) >
<!ATTLIST téléphone type (mobile|bureau|domicile) #REQUIRED >

<!ELEMENT email (#PCDATA) >

=== Ayoub-etoullali/Activites-Pratiques-XML-And-Semantic-Web/Séances/Séance 1/Prof/rep.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE repertoire SYSTEM "rep.dtd">
<repertoire maj="jhgjh">
    <contact >
        <nom></nom>
        <téléphone type="bureau"></téléphone>
        <téléphone type="bureau"></téléphone>
        <email></email>
        <email></email>
    </contact>
    <contact>
        <nom></nom>
        <téléphone type="bureau"></téléphone>
    </contact>
</repertoire>
